[package]
name = "pallet-eth2-light-client-runtime-api"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime API definition required by System RPC extensions."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", workspace = true }
sp-api = { workspace = true }
webb-proposals = { workspace = true }
eth-types = { path = "../../../crates/eth-types", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "eth-types/std",
    "webb-proposals/std"
]